-- Tạo cơ sở dữ liệu
CREATE DATABASE IF NOT EXISTS QLSINHVIEN;
USE QLSINHVIEN;

-- Bảng SINHVIEN
CREATE TABLE SINHVIEN (
    Ma_SV VARCHAR(10) PRIMARY KEY,
    HoDemSV NVARCHAR(50),
    Ngay_Sinh_SV DATE,
    SDT_SV VARCHAR(15),
    Email_SV VARCHAR(50),
    TT_Hoctap VARCHAR(20),
    Ten_SV NVARCHAR(30),
    Dia_Chi NVARCHAR(100),
    Ma_Lop VARCHAR(10)
);

-- Bảng LOPHANHCHINH
CREATE TABLE LOPHANHCHINH (
    Ma_LHP VARCHAR(10) PRIMARY KEY,
    Ma_Lop VARCHAR(10),
    Ten_Lop NVARCHAR(50),
    SI_So INT,
    Nien_Khoa VARCHAR(20),
    Ma_Khoa VARCHAR(10)
);

-- Bảng MONHOC
CREATE TABLE MONHOC (
    Ma_MH VARCHAR(10) PRIMARY KEY,
    Ten_MH NVARCHAR(100),
    So_Tiet_LT INT,
    So_Tiet_TH INT,
    So_Tin_Chi INT,
    Ma_BM VARCHAR(10)
);

-- Bảng LOPHOCPHAN
CREATE TABLE LOPHOCPHAN (
    Ma_LHP VARCHAR(10) PRIMARY KEY,
    SL_Toi_Da INT,
    Phong_Hoc VARCHAR(20),
    Lich_Hoc VARCHAR(50),
    Ma_MH VARCHAR(10),
    Ma_HK VARCHAR(10),
    Ma_GV VARCHAR(10)
);

-- Bảng HOCKY
CREATE TABLE HOCKY (
    Ma_HK VARCHAR(10) PRIMARY KEY,
    Ten_HK NVARCHAR(50),
    Nam_Hoc VARCHAR(20),
    Ky_Trong_Nam INT,
    Ngay_Bat_Dau DATE,
    Ngay_Ket_Thuc DATE
);

-- Bảng GIANGVIEN
CREATE TABLE GIANGVIEN (
    Ma_GV VARCHAR(10) PRIMARY KEY,
    Ten_GV NVARCHAR(50),
    SDT_GV VARCHAR(15),
    Ngay_Sinh_GV DATE,
    Gioi_Tinh_GV VARCHAR(5),
    Email_GV VARCHAR(50),
    Hoc_Vi VARCHAR(20),
    Ma_BM VARCHAR(10)
);

-- Bảng KHOA
CREATE TABLE KHOA (
    Ma_Khoa VARCHAR(10) PRIMARY KEY,
    Ten_Khoa NVARCHAR(100),
    Nam_TL INT,
    Phong_Khoa VARCHAR(20)
);

-- Bảng BOMON
CREATE TABLE BOMON (
    Ma_BM VARCHAR(10) PRIMARY KEY,
    Ten_BM NVARCHAR(100),
    Phong_BM VARCHAR(20),
    Email_BM VARCHAR(50),
    Ma_Khoa VARCHAR(10)
);

-- Bảng DIEM
CREATE TABLE DIEM (
    Ma_SV VARCHAR(10),
    Ma_LHP VARCHAR(10),
    Diem_CC DECIMAL(3,1),
    Diem_GK DECIMAL(3,1),
    Diem_CK DECIMAL(3,1),
    PRIMARY KEY (Ma_SV, Ma_LHP)
);

-- Bảng DANGKY
CREATE TABLE DANGKY (
    Ma_SV VARCHAR(10),
    Ma_LHP VARCHAR(10),
    PRIMARY KEY (Ma_SV, Ma_LHP)
);

-- Thêm khóa ngoại
ALTER TABLE SINHVIEN 
    ADD CONSTRAINT FK_SV_LHP FOREIGN KEY (Ma_Lop) REFERENCES LOPHANHCHINH(Ma_LHP);

ALTER TABLE LOPHANHCHINH 
    ADD CONSTRAINT FK_LHP_Khoa FOREIGN KEY (Ma_Khoa) REFERENCES KHOA(Ma_Khoa);

ALTER TABLE MONHOC 
    ADD CONSTRAINT FK_MH_BM FOREIGN KEY (Ma_BM) REFERENCES BOMON(Ma_BM);

ALTER TABLE LOPHOCPHAN 
    ADD CONSTRAINT FK_LHP_MH FOREIGN KEY (Ma_MH) REFERENCES MONHOC(Ma_MH),
    ADD CONSTRAINT FK_LHP_HK FOREIGN KEY (Ma_HK) REFERENCES HOCKY(Ma_HK),
    ADD CONSTRAINT FK_LHP_GV FOREIGN KEY (Ma_GV) REFERENCES GIANGVIEN(Ma_GV);

ALTER TABLE GIANGVIEN 
    ADD CONSTRAINT FK_GV_BM FOREIGN KEY (Ma_BM) REFERENCES BOMON(Ma_BM);

ALTER TABLE BOMON 
    ADD CONSTRAINT FK_BM_Khoa FOREIGN KEY (Ma_Khoa) REFERENCES KHOA(Ma_Khoa);

ALTER TABLE DIEM 
    ADD CONSTRAINT FK_Diem_SV FOREIGN KEY (Ma_SV) REFERENCES SINHVIEN(Ma_SV),
    ADD CONSTRAINT FK_Diem_LHP FOREIGN KEY (Ma_LHP) REFERENCES LOPHOCPHAN(Ma_LHP);

ALTER TABLE DANGKY 
    ADD CONSTRAINT FK_DK_SV FOREIGN KEY (Ma_SV) REFERENCES SINHVIEN(Ma_SV),
    ADD CONSTRAINT FK_DK_LHP FOREIGN KEY (Ma_LHP) REFERENCES LOPHOCPHAN(Ma_LHP);